# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit cnefetools.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  warning = FALSE,
  eval = FALSE
)

# Patch distill so that an explicit `last_name:` in the YAML author block
# takes precedence over the default behaviour of splitting `name` on spaces
# and using the last word (which would produce "Junior" instead of
# "Pedreira Junior").
local({
  patched <- function(authors) {
    lapply(authors, function(author) {
      if (is.null(author$name)) {
        fn <- if (!is.null(author$first_name)) author$first_name else ""
        ln <- if (!is.null(author$last_name))  author$last_name  else ""
        author$name <- trimws(paste(fn, ln))
      } else {
        names <- strsplit(author$name, "\\s+")[[1]]
        author$first_name <- paste(utils::head(names, -1), collapse = " ")
        if (is.null(author$last_name))
          author$last_name <- utils::tail(names, 1)
      }
      author
    })
  }
  utils::assignInNamespace("authors_with_first_and_last_names", patched, "distill")
})

# Helper: format inline code in captions for both PDF (LaTeX) and HTML.
cfmt <- function(x) {
  if (knitr::is_latex_output()) {
    x_esc <- gsub("_", "\\_", x, fixed = TRUE)
    x_esc <- gsub("$", "\\$", x_esc, fixed = TRUE)
    sprintf("\\texttt{%s}", x_esc)
  } else {
    sprintf("`%s`", x)
  }
}


## ----read-cnefe-example-------------------------------------------------------
library(cnefetools)

# Read as an Arrow table (default; no spatial conversion)
cnefe <- read_cnefe(
  code_muni = 2919207,
  year      = 2022,
  cache     = TRUE,
  verbose   = TRUE,
  output    = 'arrow'    # default
)

# Read as an sf point object with SIRGAS 2000 coordinates (EPSG:4674)
cnefe_sf <- read_cnefe(
  code_muni = 2919207,
  year      = 2022,
  cache     = TRUE,
  verbose   = TRUE,
  output    = 'sf'
) 


## ----cnefe-preview, echo=-3, eval=TRUE, cache=TRUE----------------------------
library(dplyr)

cnefe <- cnefetools::read_cnefe(
  code_muni = 2919207, verbose = FALSE
)
cnefe |>
  select(NOM_TIPO_SEGLOGR, NOM_SEGLOGR, CEP, COD_ESPECIE,
         LONGITUDE, LATITUDE, DSC_ESTABELECIMENTO) |>
  collect() |> 
  head()


## ----fig-read-cnefe, echo=FALSE, eval=TRUE, cache=TRUE, fig.cap="Educational establishment addresses geocoded in Lauro de Freitas, Bahia.", fig.alt="Map of Lauro de Freitas municipality showing educational establishment address points as blue dots distributed across the urban area, with the municipal boundary outlined in black on a light grey background.", fig.width=6, fig.height=5, out.width="100%"----
library(geobr)
library(ggplot2)
library(sf)
library(dplyr)

# Lauro de Freitas boundary
muni_ldf <- geobr::read_municipality(code_muni = 2919207,
                                     year = 2020,
                                     simplified = FALSE,
                                     showProgress = FALSE)

# CNEFE educational establishments only (COD_ESPECIE == 4)
educational <- cnefetools::read_cnefe(
  code_muni = 2919207, output = "sf", verbose = FALSE
) |>
  dplyr::filter(COD_ESPECIE == 4)

ggplot() +
  geom_sf(data = muni_ldf, fill = "grey95", color = "black", linewidth = 0.7) +
  geom_sf(data = educational, size = 0.8, alpha = 0.7, color = "#2166AC") +
  theme_void() +
  theme(plot.background = element_rect(fill = "white", color = NA))


## ----counts-hex-example-------------------------------------------------------
# Count addresses per H3 hexagon at resolution 9
hex_counts <- cnefe_counts(
  code_muni     = 2919207,
  year          = 2022,
  cache         = TRUE,
  h3_resolution = 9,
  verbose       = TRUE,
  backend       = "duckdb"
)

# Count per user-supplied polygon (e.g., neighborhoods)
library(geobr)
library(dplyr)

nei <- read_neighborhood(year = 2022) |> 
  filter(code_muni == 2919207)

poly_counts <- cnefe_counts(
  code_muni    = 2919207,
  year         = 2022,
  cache        = TRUE,
  polygon      = nei,
  crs_output   = NULL,
  verbose      = TRUE,
  backend      = "duckdb"
)


## ----fig-counts, echo=FALSE, eval=TRUE, cache=TRUE, fig.cap=paste0("Private household address counts (", cfmt("addr_type1"), ") aggregated to H3 hexagons at resolution~8 (left) and to neighborhoods (right) for Lauro de Freitas, Bahia."), fig.alt="Two side-by-side choropleth maps of Lauro de Freitas. The left map shows private household address counts aggregated to H3 hexagons at resolution 8; the right map shows the same counts aggregated to neighborhoods. Both maps use a green-to-yellow colour scale where darker green indicates lower counts and bright yellow indicates higher counts.", fig.width=10, fig.height=5, out.width="100%"----
library(geobr)
library(ggplot2)
library(sf)
library(dplyr)
library(patchwork)
library(paletteer)

# Lauro de Freitas boundary
muni_ldf <- geobr::read_municipality(code_muni = 2919207, year = 2020,
                                     showProgress = FALSE)

# Neighborhoods of Lauro de Freitas
nei <- geobr::read_neighborhood(year = 2022, showProgress = FALSE) |>
  dplyr::filter(name_muni == "Lauro de Freitas")

# Address counts per H3 hexagon at resolution 8
hex8 <- cnefetools::cnefe_counts(
  code_muni     = 2919207,
  h3_resolution = 8,
  verbose       = FALSE
)

# Address counts per neighborhood
poly_counts <- cnefetools::cnefe_counts(
  code_muni    = 2919207,
  polygon      = nei,
  verbose      = FALSE
)

p1 <- ggplot(hex8) +
  geom_sf(aes(fill = addr_type1), color = NA)+
  paletteer::scale_fill_paletteer_c("grDevices::ag_GrnYl",
                                    direction = 1, 
                                    name = "Count")+
  labs(title = "H3 resolution 8") +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "right",
        plot.background = element_rect(fill = "white", color = NA))

p2 <- ggplot() +
  geom_sf(data = poly_counts, aes(fill = addr_type1), color = "white",
          linewidth = 0.2) +
  paletteer::scale_fill_paletteer_c("grDevices::ag_GrnYl",
                                    direction = 1, 
                                    name = "Count")+
  labs(title = "Neighborhoods") +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "right",
        plot.background = element_rect(fill = "white", color = NA))

p1 + p2


## ----lumi-example-------------------------------------------------------------
# Compute all indices on H3 hexagons at resolution 9 (default)
lumi_hex <- compute_lumi(
  code_muni     = 2919207,
  year          = 2022,
  cache         = TRUE,
  h3_resolution = 9,
  verbose       = TRUE,
  backend       = "duckdb"
)

# Compute on user-supplied polygons
lumi_poly <- compute_lumi(
  code_muni    = 2919207,
  year         = 2022,
  cache        = TRUE,
  polygon      = nei,
  crs_output   = NULL,
  verbose      = TRUE,
  backend      = "duckdb"
)


## ----fig-bgbi, echo=FALSE, eval=TRUE, cache=TRUE, fig.cap="Bidirectional Global-centered Balance Index (BGBI) for Lauro de Freitas, Bahia, aggregated to H3 hexagons at resolution~8 (left) and to neighborhoods (right). Green cells indicate a local residential share above the citywide average ($p_i > P$); pink cells indicate non-residential dominance ($p_i < P$); white cells are near the citywide baseline.", fig.alt="Two side-by-side choropleth maps of Lauro de Freitas showing the BGBI index. The left map aggregates to H3 hexagons at resolution 8 and the right map aggregates to neighborhoods. Green areas indicate a local residential share above the citywide average, pink areas indicate non-residential dominance, and white or neutral areas are near the citywide baseline.", fig.width=10, fig.height=5, out.width="100%"----
library(geobr)
library(ggplot2)
library(sf)
library(dplyr)
library(patchwork)

# Lauro de Freitas boundary
muni_ldf <- geobr::read_municipality(code_muni = 2919207, year = 2020,
                                     showProgress = FALSE)

# Neighborhoods of Lauro de Freitas
nei <- geobr::read_neighborhood(year = 2022, showProgress = FALSE) |>
  dplyr::filter(name_muni == "Lauro de Freitas")

# BGBI per H3 hexagon at resolution 8
lumi_hex <- cnefetools::compute_lumi(
  code_muni     = 2919207,
  h3_resolution = 8,
  verbose       = FALSE
)

# BGBI per neighborhood
lumi_poly <- cnefetools::compute_lumi(
  code_muni    = 2919207,
  polygon      = nei,
  verbose      = FALSE
)

tropic_colors <- paletteer::paletteer_c("grDevices::Tropic", n = 256, direction = -1)

p1 <- ggplot(lumi_hex) +
  geom_sf(aes(fill = bgbi), color = NA, linetype = 1) +
  geom_sf(data = dplyr::filter(lumi_hex, is.na(bgbi)),
          aes(linetype = "No data (NA)"),
          fill = NA, color = NA) +
  scale_fill_gradientn(
    colours  = tropic_colors,
    limits   = c(-1, 1),
    na.value = "gray40",
    name     = "BGBI"
  ) +
  scale_linetype_manual(
    values = 0, name = NULL,
    guide  = guide_legend(
      override.aes = list(fill = "grey40", color = NA, linewidth = 0)
    )
  ) +
  labs(title = "H3 resolution 8") +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "right",
        legend.box = "vertical",
        plot.background = element_rect(fill = "white", color = NA))

p2 <- ggplot() +
  geom_sf(data = lumi_poly, aes(fill = bgbi),
          color = "white", linewidth = 0.2, linetype = 1) +
  geom_sf(data = dplyr::filter(lumi_poly, is.na(bgbi)),
          aes(linetype = "No data (NA)"),
          fill = NA, color = NA) +
  scale_fill_gradientn(
    colours  = tropic_colors,
    limits   = c(-1, 1),
    na.value = "grey80",
    name     = "BGBI"
  ) +
  scale_linetype_manual(
    values = 0, name = NULL,
    guide  = guide_legend(
      override.aes = list(fill = "grey80", color = "white", linewidth = 0.2)
    )
  ) +
  labs(title = "Neighborhoods") +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "right",
        legend.box = "vertical",
        plot.background = element_rect(fill = "white", color = NA))

p1 + p2


## ----tab-tracts-vars, eval=TRUE, echo=FALSE-----------------------------------
library(cnefetools)
knitr::kable(
  tracts_variables_ref[, c("var_cnefetools", "code_var_ibge", "table_ibge")],
  col.names = c("Variable", "Variable code", "Source table"),
  caption = if (knitr::is_latex_output()) {
    paste0(
      "Variables supported by \\texttt{tracts\\_to\\_h3()} and",
      " \\texttt{tracts\\_to\\_polygon()}, with their variable codes and",
     " source tables, with codes as used by censobr. Portuguese descriptions",
      " are available in \\texttt{tracts\\_variables\\_ref\\$desc\\_var\\_ibge}."
    )
  } else {
    paste0(
      "Variables supported by `tracts_to_h3()` and",
      " `tracts_to_polygon()`, with their variable codes and",
      " source tables, with codes as used by censobr. Portuguese descriptions",
      " are available in `tracts_variables_ref$desc_var_ibge`."
    )
  },
  booktabs = TRUE
)


## ----tab-alloc, eval=TRUE, echo=FALSE-----------------------------------------
if (knitr::is_latex_output()) {
  alloc_df <- data.frame(
    Variable = c(
      "\\texttt{pop\\_ph}",
      "\\texttt{pop\\_ch}",
      "\\texttt{n\\_resp}",
      "\\texttt{male}, \\texttt{female}, \\texttt{age\\_*}, \\texttt{race\\_*}",
      "\\texttt{avg\\_inc\\_resp}"
    ),
    `Eligible type` = c(
      "Type 1 (private)",
      "Type 2 (collective)",
      "Type 1 (private)",
      "Type 1; else Type 2",
      "Type 1 (private)"
    ),
    `Per-point value` = c(
      "total / n\\_dom\\_p",
      "total / n\\_dom\\_c",
      "total / n\\_dom\\_p",
      "total / n\\_eligible",
      "tract avg (assigned)"
    ),
    `Aggregated as` = c("SUM", "SUM", "SUM", "SUM", "MEAN"),
    check.names = FALSE
  )
  knitr::kable(
    alloc_df,
    escape  = FALSE,
    booktabs = TRUE,
    caption = "Allocation rules applied during dasymetric interpolation. \\texttt{n\\_dom\\_p} and \\texttt{n\\_dom\\_c} are counts of matched type-1 and type-2 CNEFE dwelling points per census tract."
  ) |>
    kableExtra::kable_styling(latex_options = "scale_down")
} else {
  alloc_df <- data.frame(
    Variable = c(
      "`pop_ph`", "`pop_ch`", "`n_resp`",
      "`male`, `female`, `age_*`, `race_*`",
      "`avg_inc_resp`"
    ),
    `Eligible type` = c(
      "Type 1 (private)",
      "Type 2 (collective)",
      "Type 1 (private)",
      "Type 1; else Type 2",
      "Type 1 (private)"
    ),
    `Per-point value` = c(
      "total / `n_dom_p`",
      "total / `n_dom_c`",
      "total / `n_dom_p`",
      "total / n_eligible",
      "tract avg (assigned)"
    ),
    `Aggregated as` = c("SUM", "SUM", "SUM", "SUM", "MEAN"),
    check.names = FALSE
  )
  knitr::kable(
    alloc_df,
    booktabs = TRUE,
    caption = "Allocation rules applied during dasymetric interpolation. `n_dom_p` and `n_dom_c` are counts of matched type-1 and type-2 CNEFE dwelling points per census tract."
  )
}


## ----tracts-example-----------------------------------------------------------
# Interpolate population in private and collective households to H3 hexagons
hex_pop <- tracts_to_h3(
  code_muni     = 2919207,
  h3_resolution = 9,
  vars          = c("pop_ph", "pop_ch"),
  cache         = TRUE,
  verbose       = TRUE
)

# Interpolate to user-supplied polygons (e.g., traffic zones)
poly_pop <- tracts_to_polygon(
  code_muni = 2919207,
  polygon   = nei,                          # Lauro de Freitas' neighborhoods 
  vars      = c("pop_ph", "avg_inc_resp"),
  cache         = TRUE,
  verbose       = TRUE
)


## ----fig-pop, echo=FALSE, eval=TRUE, cache=TRUE, fig.cap=paste0("Dasymetric estimates of private-household population (", cfmt("pop_ph"), ") for Lauro de Freitas, Bahia, interpolated from 2022 census tract totals to H3 hexagons at resolution~8 (left) and to neighborhoods (right) using CNEFE dwelling points as ancillary data."), fig.alt="Two side-by-side choropleth maps of Lauro de Freitas showing dasymetric estimates of private-household population. The left map shows estimates on H3 hexagons at resolution 8 and the right map shows estimates on neighborhoods. Both use a green-to-yellow colour scale where brighter yellow indicates higher population counts.", fig.width=10, fig.height=5, out.width="100%"----
library(geobr)
library(ggplot2)
library(sf)
library(dplyr)
library(patchwork)

# Lauro de Freitas boundary
muni_ldf <- geobr::read_municipality(code_muni = 2919207, year = 2020,
                                     showProgress = FALSE)

# neighborhoods of Lauro de Freitas
nei <- geobr::read_neighborhood(year = 2022, showProgress = FALSE) |>
  dplyr::filter(name_muni == "Lauro de Freitas")

# Dasymetric population to H3 hexagons at resolution 8
hex_pop <- cnefetools::tracts_to_h3(
  code_muni     = 2919207,
  h3_resolution = 8,
  vars          = "pop_ph",
  verbose       = FALSE
)

# Dasymetric population to neighborhoods
poly_pop <- cnefetools::tracts_to_polygon(
  code_muni = 2919207,
  polygon   = nei,
  vars      = "pop_ph",
  verbose   = FALSE
)

p1 <- ggplot(hex_pop) +
  geom_sf(aes(fill = pop_ph), color = NA) +
  paletteer::scale_fill_paletteer_c("grDevices::ag_GrnYl",
                                    direction = 1)+
  labs(title = "H3 resolution 8") +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "right",
        plot.background = element_rect(fill = "white", color = NA))

p2 <- ggplot() +
  geom_sf(data = poly_pop, aes(fill = pop_ph), color = "white",
          linewidth = 0.2) +
  paletteer::scale_fill_paletteer_c("grDevices::ag_GrnYl",direction = 1)+
  labs(title = "Neighborhoods") +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "right",
        plot.background = element_rect(fill = "white", color = NA))

p1 + p2


## ----diag-nei, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE----
nei <- geobr::read_neighborhood(year = 2022, showProgress = FALSE) |>
  dplyr::filter(name_muni == "Lauro de Freitas")


## ----tracts-diag, eval=TRUE, echo=TRUE, message=TRUE, warning=FALSE, cache=TRUE, dependson="diag-nei"----
poly_diag <- cnefetools::tracts_to_polygon(
  code_muni = 2919207,
  polygon   = nei,
  vars      = c("pop_ph", "avg_inc_resp"),
  verbose   = FALSE
)


## ----util-docs----------------------------------------------------------------
cnefe_dictionary()  # opens the Excel data dictionary
cnefe_doc()         # opens the IBGE methodological PDF


## ----util-cache---------------------------------------------------------------
clear_cache_muni()          # delete all cached CNEFE files
clear_cache_muni(2919207)   # delete only the file for Lauro de Freitas-BA

clear_cache_tracts()        # delete all cached census tract Parquets
clear_cache_tracts("BA")    # delete only the Parquet for the state of Bahia ("BA")


## ----util-export--------------------------------------------------------------
# Write Lauro de Freitas-BA to a project folder as Parquet
path <- cnefe_export(2919207, path = "data/cnefe")

# Read it back later without downloading anything
cnefe <- read_cnefe(file = path)


## ----fig-bench-cities, echo=FALSE, eval=TRUE, out.width="70%", fig.align="center", fig.alt="Grouped bar chart comparing elapsed time in seconds for cnefe_counts() at H3 resolution 8 across three municipalities of increasing size: Vitória da Conquista-BA (roughly 200,000 addresses), Curitiba-PR (roughly 900,000 addresses), and São Paulo-SP (roughly 5.7 million addresses). For each municipality, two bars represent the DuckDB and pure-R backends; the DuckDB bar is shorter for larger municipalities, indicating increasing speedup with dataset size.", fig.cap=paste0("Elapsed time (s) for ", cfmt("cnefe_counts()"), " at H3 resolution~8, by municipality size, comparing the DuckDB and pure-R backends.")----
knitr::include_graphics("figures/bench-cities.png")


## ----fig-bench-h3, echo=FALSE, eval=TRUE, out.width="70%", fig.align="center", fig.alt="Grouped bar chart comparing elapsed time in seconds for cnefe_counts() on Curitiba-PR across three H3 resolutions: 7 (coarse), 9 (medium), and 11 (fine). For each resolution, two bars represent the DuckDB and pure-R backends; the DuckDB speedup decreases at finer resolutions as H3 indexing cost becomes dominant.", fig.cap=paste0("Elapsed time (s) for ", cfmt("cnefe_counts()"), " on Curitiba-PR, by H3 resolution.")----
knitr::include_graphics("figures/bench-h3.png")


## ----fig-bench-memory, echo=FALSE, eval=TRUE, out.width="70%", fig.align="center", fig.alt="Grouped bar chart comparing peak memory in gigabytes for cnefe_counts() at H3 resolution 8 across three municipalities of increasing size. For each municipality, two bars represent the DuckDB and pure-R backends; the DuckDB bars stay nearly constant at or below 0.7 GB while the pure-R bars grow with municipality size, reaching about 9 GB for São Paulo.", fig.cap=paste0("Peak memory (GB) for ", cfmt("cnefe_counts()"), " at H3 resolution~8, by municipality size, comparing the DuckDB and pure-R backends.")----
knitr::include_graphics("figures/bench-memory.png")

